# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

Dotenv.load('../.env.local')

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :upload_sauce do
    saucelabs_upload(
    user_name: ENV['SAUCELABS_USERNAME'],
    api_key:  ENV['SAUCELABS_API_KEY'],
    app_name: "App.ipa",
    app_description: "App lane test 1",
    file: "./apps/App.ipa",
    region: 'eu-central-1'
)
  end
end
